// AUTO-GENERATED by scripts/generateAchievementSeed.mjs — do not edit manually
import type { Category } from '@/types/achievement';

export interface AchievementSeedRow {
  id: string;
  category: Category;
  prerequisite_id: string | null;
  rarity: string;
  trigger_type: string;
  trigger_goal: number;
  reward_points: number;
  is_hidden: number;
  prompt_photo: number;
  icon: string;
}

export interface TriggerSeedRow {
  achievement_id: string;
  event_type: string;
  condition_json: string | null;
}

export const ACHIEVEMENT_SEED: AchievementSeedRow[] = [
  {
    "id": "checkin_1",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "checkin_count",
    "trigger_goal": 1,
    "reward_points": 10,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "📍"
  },
  {
    "id": "checkin_3",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "checkin_count",
    "trigger_goal": 3,
    "reward_points": 15,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "📍"
  },
  {
    "id": "checkin_5",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "checkin_count",
    "trigger_goal": 5,
    "reward_points": 25,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "📍"
  },
  {
    "id": "checkin_10",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "checkin_count",
    "trigger_goal": 10,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "📍"
  },
  {
    "id": "checkin_25",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "checkin_count",
    "trigger_goal": 25,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "📍"
  },
  {
    "id": "checkin_50",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "checkin_count",
    "trigger_goal": 50,
    "reward_points": 200,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "📍"
  },
  {
    "id": "explore_7continents",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Legendary",
    "trigger_type": "auto_track",
    "trigger_goal": 7,
    "reward_points": 1000,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_50countries",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Legendary",
    "trigger_type": "auto_track",
    "trigger_goal": 50,
    "reward_points": 2000,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_10countries",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "auto_track",
    "trigger_goal": 10,
    "reward_points": 200,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_5countries",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "auto_track",
    "trigger_goal": 5,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_3continents",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "auto_track",
    "trigger_goal": 3,
    "reward_points": 500,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_dateline",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_missed_flight",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_island",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_mountain",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "auto_track",
    "trigger_goal": 1,
    "reward_points": 75,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_solo",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_ocean",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 150,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_first_abroad",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_japan",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "auto_track",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_europe",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "auto_track",
    "trigger_goal": 1,
    "reward_points": 75,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_africa",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "auto_track",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_south_america",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "auto_track",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_antarctica",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "auto_track",
    "trigger_goal": 1,
    "reward_points": 500,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_australia",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "auto_track",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_asia",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "auto_track",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_north_america",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "auto_track",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_oceania",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "auto_track",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_capital",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 30,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_unesco",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_temple",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 20,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_night_market",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 20,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_hot_spring",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 30,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_beach",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 20,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_museum",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 30,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_airport",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 30,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_cruise",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 75,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_border",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_canyon",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_volcano",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_lake",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 30,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_tower",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 30,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_tokyo_tower",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_great_wall",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 200,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_venice",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 150,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "ocean_pacific",
    "category": "Collection",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 200,
    "is_hidden": 1,
    "prompt_photo": 0,
    "icon": "🌊"
  },
  {
    "id": "ocean_atlantic",
    "category": "Collection",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 200,
    "is_hidden": 1,
    "prompt_photo": 0,
    "icon": "🌊"
  },
  {
    "id": "ocean_indian",
    "category": "Collection",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 200,
    "is_hidden": 1,
    "prompt_photo": 0,
    "icon": "🌊"
  },
  {
    "id": "ocean_arctic",
    "category": "Collection",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 500,
    "is_hidden": 1,
    "prompt_photo": 0,
    "icon": "🌊"
  },
  {
    "id": "ocean_southern",
    "category": "Collection",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 500,
    "is_hidden": 1,
    "prompt_photo": 0,
    "icon": "🌊"
  },
  {
    "id": "career_phd",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 200,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💼"
  },
  {
    "id": "career_graduate",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💼"
  },
  {
    "id": "career_house",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 300,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💼"
  },
  {
    "id": "career_first_job",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💼"
  },
  {
    "id": "career_365_ontime",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 150,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💼"
  },
  {
    "id": "career_masters",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💼"
  },
  {
    "id": "career_bachelor",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💼"
  },
  {
    "id": "career_fired",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 75,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💼"
  },
  {
    "id": "career_promotion",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💼"
  },
  {
    "id": "career_startup",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 200,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💼"
  },
  {
    "id": "career_raise",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💼"
  },
  {
    "id": "career_quit",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 75,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💼"
  },
  {
    "id": "career_meeting_hell",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 30,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💼"
  },
  {
    "id": "daily_lottery",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "daily_social",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 20,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "daily_pets",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 2,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "daily_earlybird",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "auto_track",
    "trigger_goal": 1,
    "reward_points": 30,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "daily_cook",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 10,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "daily_binge",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 30,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "daily_allnighter",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "auto_track",
    "trigger_goal": 1,
    "reward_points": 30,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "daily_exercise_30",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 30,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "daily_read_10",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 10,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "daily_no_phone",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "auto_track",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "daily_stranger",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 30,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "daily_umbrella",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 10,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "daily_puzzle",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 20,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "daily_late",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 20,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "daily_spicy",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 30,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "daily_karaoke",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 20,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "daily_fall_down",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 15,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "epic_eclipse",
    "category": "Combat",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 200,
    "is_hidden": 1,
    "prompt_photo": 0,
    "icon": "⭐"
  },
  {
    "id": "epic_survive",
    "category": "Combat",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 500,
    "is_hidden": 1,
    "prompt_photo": 0,
    "icon": "⭐"
  },
  {
    "id": "epic_newborn",
    "category": "Combat",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 500,
    "is_hidden": 1,
    "prompt_photo": 0,
    "icon": "⭐"
  },
  {
    "id": "epic_northernlights",
    "category": "Combat",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 500,
    "is_hidden": 1,
    "prompt_photo": 0,
    "icon": "⭐"
  },
  {
    "id": "epic_milkyway",
    "category": "Combat",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 300,
    "is_hidden": 1,
    "prompt_photo": 0,
    "icon": "⭐"
  },
  {
    "id": "epic_earthquake",
    "category": "Combat",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "auto_track",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "⭐"
  },
  {
    "id": "weather_storm",
    "category": "Combat",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "auto_track",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🌦️"
  },
  {
    "id": "weather_rain",
    "category": "Combat",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "auto_track",
    "trigger_goal": 1,
    "reward_points": 30,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🌦️"
  },
  {
    "id": "weather_extreme_heat",
    "category": "Combat",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "auto_track",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🌦️"
  },
  {
    "id": "weather_lightning",
    "category": "Combat",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "auto_track",
    "trigger_goal": 1,
    "reward_points": 75,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🌦️"
  },
  {
    "id": "epic_double_rainbow",
    "category": "Combat",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 200,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "⭐"
  },
  {
    "id": "epic_meteor",
    "category": "Combat",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 200,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "⭐"
  },
  {
    "id": "epic_first_date",
    "category": "Combat",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "⭐"
  },
  {
    "id": "epic_concert",
    "category": "Combat",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 150,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "⭐"
  },
  {
    "id": "health_marathon",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 200,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💪"
  },
  {
    "id": "health_blood",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💪"
  },
  {
    "id": "health_10k",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💪"
  },
  {
    "id": "health_no_sugar",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 75,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💪"
  },
  {
    "id": "health_meditate",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💪"
  },
  {
    "id": "health_gym",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 30,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💪"
  },
  {
    "id": "health_pushup_50",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💪"
  },
  {
    "id": "health_weight_loss",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 200,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💪"
  },
  {
    "id": "health_sleep_8h",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💪"
  },
  {
    "id": "transport_license",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🚗"
  },
  {
    "id": "transport_first_car",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🚗"
  },
  {
    "id": "transport_bike",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🚗"
  },
  {
    "id": "transport_roadtrip",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🚗"
  },
  {
    "id": "transport_no_accident",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🚗"
  },
  {
    "id": "transport_uber_100",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🚗"
  },
  {
    "id": "transport_bike_100",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 150,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🚗"
  },
  {
    "id": "health_yoga",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 30,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💪"
  },
  {
    "id": "health_vegan",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💪"
  },
  {
    "id": "health_plank_5min",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💪"
  },
  {
    "id": "daily_look_up",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 20,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "daily_suntan",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 15,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "daily_chopsticks",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "career_overtime_hell",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💼"
  },
  {
    "id": "career_presentation",
    "category": "Mastery",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "💼"
  },
  {
    "id": "explore_bucket_list",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 300,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_sky_lantern",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_snow",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_desert",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 150,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_jungle",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 200,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_underwater",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Epic",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 200,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "explore_camping",
    "category": "Exploration",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 75,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "🗺️"
  },
  {
    "id": "daily_diy",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Common",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 30,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "daily_fix",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "daily_plant",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "daily_tattoo",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 100,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  },
  {
    "id": "daily_photo_album",
    "category": "Social",
    "prerequisite_id": null,
    "rarity": "Rare",
    "trigger_type": "manual",
    "trigger_goal": 1,
    "reward_points": 50,
    "is_hidden": 0,
    "prompt_photo": 0,
    "icon": "☀️"
  }
];

export const TRIGGER_SEED: TriggerSeedRow[] = [
  {
    "achievement_id": "checkin_1",
    "event_type": "checkin_count",
    "condition_json": null
  },
  {
    "achievement_id": "checkin_3",
    "event_type": "checkin_count",
    "condition_json": null
  },
  {
    "achievement_id": "checkin_5",
    "event_type": "checkin_count",
    "condition_json": null
  },
  {
    "achievement_id": "checkin_10",
    "event_type": "checkin_count",
    "condition_json": null
  },
  {
    "achievement_id": "checkin_25",
    "event_type": "checkin_count",
    "condition_json": null
  },
  {
    "achievement_id": "checkin_50",
    "event_type": "checkin_count",
    "condition_json": null
  },
  {
    "achievement_id": "explore_7continents",
    "event_type": "continent_count",
    "condition_json": null
  },
  {
    "achievement_id": "explore_50countries",
    "event_type": "country_count",
    "condition_json": null
  },
  {
    "achievement_id": "explore_10countries",
    "event_type": "country_count",
    "condition_json": null
  },
  {
    "achievement_id": "explore_5countries",
    "event_type": "country_count",
    "condition_json": null
  },
  {
    "achievement_id": "explore_3continents",
    "event_type": "continent_count",
    "condition_json": null
  },
  {
    "achievement_id": "explore_dateline",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_missed_flight",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_island",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_mountain",
    "event_type": "altitude_checked",
    "condition_json": "{\"minMeters\":2500}"
  },
  {
    "achievement_id": "explore_solo",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_ocean",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_first_abroad",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_japan",
    "event_type": "checkin_completed",
    "condition_json": "{\"country\":\"Japan\"}"
  },
  {
    "achievement_id": "explore_europe",
    "event_type": "checkin_completed",
    "condition_json": "{\"continent\":\"Europe\"}"
  },
  {
    "achievement_id": "explore_africa",
    "event_type": "checkin_completed",
    "condition_json": "{\"continent\":\"Africa\"}"
  },
  {
    "achievement_id": "explore_south_america",
    "event_type": "checkin_completed",
    "condition_json": "{\"continent\":\"South America\"}"
  },
  {
    "achievement_id": "explore_antarctica",
    "event_type": "checkin_completed",
    "condition_json": "{\"continent\":\"Antarctica\"}"
  },
  {
    "achievement_id": "explore_australia",
    "event_type": "checkin_completed",
    "condition_json": "{\"country\":\"Australia\"}"
  },
  {
    "achievement_id": "explore_asia",
    "event_type": "checkin_completed",
    "condition_json": "{\"continent\":\"Asia\"}"
  },
  {
    "achievement_id": "explore_north_america",
    "event_type": "checkin_completed",
    "condition_json": "{\"continent\":\"North America\"}"
  },
  {
    "achievement_id": "explore_oceania",
    "event_type": "checkin_completed",
    "condition_json": "{\"continent\":\"Oceania\"}"
  },
  {
    "achievement_id": "explore_capital",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_unesco",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_temple",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_night_market",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_hot_spring",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_beach",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_museum",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_airport",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_cruise",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_border",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_canyon",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_volcano",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_lake",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_tower",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_tokyo_tower",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_great_wall",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_venice",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "ocean_pacific",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "ocean_atlantic",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "ocean_indian",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "ocean_arctic",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "ocean_southern",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "career_phd",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "career_graduate",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "career_house",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "career_first_job",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "career_365_ontime",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "career_masters",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "career_bachelor",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "career_fired",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "career_promotion",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "career_startup",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "career_raise",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "career_quit",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "career_meeting_hell",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "daily_lottery",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "daily_social",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "daily_pets",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "daily_earlybird",
    "event_type": "time_specific",
    "condition_json": "{\"hourMax\":5}"
  },
  {
    "achievement_id": "daily_cook",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "daily_binge",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "daily_allnighter",
    "event_type": "screentime_checked",
    "condition_json": "{\"result\":\"allnighter\"}"
  },
  {
    "achievement_id": "daily_exercise_30",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "daily_read_10",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "daily_no_phone",
    "event_type": "screentime_checked",
    "condition_json": "{\"result\":\"no_phone\"}"
  },
  {
    "achievement_id": "daily_stranger",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "daily_umbrella",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "daily_puzzle",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "daily_late",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "daily_spicy",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "daily_karaoke",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "daily_fall_down",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "epic_eclipse",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "epic_survive",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "epic_newborn",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "epic_northernlights",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "epic_milkyway",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "epic_earthquake",
    "event_type": "earthquake_felt",
    "condition_json": null
  },
  {
    "achievement_id": "weather_storm",
    "event_type": "weather_checked",
    "condition_json": "{\"condition\":\"storm\"}"
  },
  {
    "achievement_id": "weather_rain",
    "event_type": "weather_checked",
    "condition_json": "{\"condition\":\"rain\"}"
  },
  {
    "achievement_id": "weather_extreme_heat",
    "event_type": "weather_checked",
    "condition_json": "{\"condition\":\"extreme_heat\"}"
  },
  {
    "achievement_id": "weather_lightning",
    "event_type": "weather_checked",
    "condition_json": "{\"condition\":\"lightning\"}"
  },
  {
    "achievement_id": "epic_double_rainbow",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "epic_meteor",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "epic_first_date",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "epic_concert",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "health_marathon",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "health_blood",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "health_10k",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "health_no_sugar",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "health_meditate",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "health_gym",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "health_pushup_50",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "health_weight_loss",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "health_sleep_8h",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "transport_license",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "transport_first_car",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "transport_bike",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "transport_roadtrip",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "transport_no_accident",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "transport_uber_100",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "transport_bike_100",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "health_yoga",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "health_vegan",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "health_plank_5min",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "daily_look_up",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "daily_suntan",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "daily_chopsticks",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "career_overtime_hell",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "career_presentation",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_bucket_list",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_sky_lantern",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_snow",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_desert",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_jungle",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_underwater",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "explore_camping",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "daily_diy",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "daily_fix",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "daily_plant",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "daily_tattoo",
    "event_type": "manual_confirm",
    "condition_json": null
  },
  {
    "achievement_id": "daily_photo_album",
    "event_type": "manual_confirm",
    "condition_json": null
  }
];

export const ACHIEVEMENT_TRANSLATIONS: [string, string, string, string, string][] = [
  [
    "achievement",
    "checkin_1",
    "en",
    "title",
    "Checkin 1"
  ],
  [
    "achievement",
    "checkin_1",
    "en",
    "description",
    "Check in at 1 different location"
  ],
  [
    "achievement",
    "checkin_1",
    "zh-TW",
    "title",
    "初次打卡"
  ],
  [
    "achievement",
    "checkin_1",
    "zh-TW",
    "description",
    "在 1 個地點打卡"
  ],
  [
    "achievement",
    "checkin_3",
    "en",
    "title",
    "Checkin 3"
  ],
  [
    "achievement",
    "checkin_3",
    "en",
    "description",
    "Check in at 3 different locations"
  ],
  [
    "achievement",
    "checkin_3",
    "zh-TW",
    "title",
    "三度到訪"
  ],
  [
    "achievement",
    "checkin_3",
    "zh-TW",
    "description",
    "在 3 個不同地點打卡"
  ],
  [
    "achievement",
    "checkin_5",
    "en",
    "title",
    "Checkin 5"
  ],
  [
    "achievement",
    "checkin_5",
    "en",
    "description",
    "Check in at 5 different locations"
  ],
  [
    "achievement",
    "checkin_5",
    "zh-TW",
    "title",
    "五方雲遊"
  ],
  [
    "achievement",
    "checkin_5",
    "zh-TW",
    "description",
    "在 5 個不同地點打卡"
  ],
  [
    "achievement",
    "checkin_10",
    "en",
    "title",
    "Checkin 10"
  ],
  [
    "achievement",
    "checkin_10",
    "en",
    "description",
    "Check in at 10 different locations"
  ],
  [
    "achievement",
    "checkin_10",
    "zh-TW",
    "title",
    "十全打卡"
  ],
  [
    "achievement",
    "checkin_10",
    "zh-TW",
    "description",
    "在 10 個不同地點打卡"
  ],
  [
    "achievement",
    "checkin_25",
    "en",
    "title",
    "Checkin 25"
  ],
  [
    "achievement",
    "checkin_25",
    "en",
    "description",
    "Check in at 25 different locations"
  ],
  [
    "achievement",
    "checkin_25",
    "zh-TW",
    "title",
    "足跡遍布"
  ],
  [
    "achievement",
    "checkin_25",
    "zh-TW",
    "description",
    "在 25 個不同地點打卡"
  ],
  [
    "achievement",
    "checkin_50",
    "en",
    "title",
    "Checkin 50"
  ],
  [
    "achievement",
    "checkin_50",
    "en",
    "description",
    "Check in at 50 different locations"
  ],
  [
    "achievement",
    "checkin_50",
    "zh-TW",
    "title",
    "打卡之王"
  ],
  [
    "achievement",
    "checkin_50",
    "zh-TW",
    "description",
    "在 50 個不同地點打卡"
  ],
  [
    "achievement",
    "explore_7continents",
    "en",
    "title",
    "Explore 7continents"
  ],
  [
    "achievement",
    "explore_7continents",
    "en",
    "description",
    "Visit 7 different continents"
  ],
  [
    "achievement",
    "explore_7continents",
    "zh-TW",
    "title",
    "征服七大洲"
  ],
  [
    "achievement",
    "explore_7continents",
    "zh-TW",
    "description",
    "踏上 7 大洲"
  ],
  [
    "achievement",
    "explore_50countries",
    "en",
    "title",
    "Explore 50countries"
  ],
  [
    "achievement",
    "explore_50countries",
    "en",
    "description",
    "Visit 50 different countries"
  ],
  [
    "achievement",
    "explore_50countries",
    "zh-TW",
    "title",
    "環遊世界"
  ],
  [
    "achievement",
    "explore_50countries",
    "zh-TW",
    "description",
    "造訪 50 個國家"
  ],
  [
    "achievement",
    "explore_10countries",
    "en",
    "title",
    "Explore 10countries"
  ],
  [
    "achievement",
    "explore_10countries",
    "en",
    "description",
    "Visit 10 different countries"
  ],
  [
    "achievement",
    "explore_10countries",
    "zh-TW",
    "title",
    "旅遊達人"
  ],
  [
    "achievement",
    "explore_10countries",
    "zh-TW",
    "description",
    "造訪 10 個國家"
  ],
  [
    "achievement",
    "explore_5countries",
    "en",
    "title",
    "Explore 5countries"
  ],
  [
    "achievement",
    "explore_5countries",
    "en",
    "description",
    "Visit 5 different countries"
  ],
  [
    "achievement",
    "explore_5countries",
    "zh-TW",
    "title",
    "國際旅人"
  ],
  [
    "achievement",
    "explore_5countries",
    "zh-TW",
    "description",
    "造訪 5 個國家"
  ],
  [
    "achievement",
    "explore_3continents",
    "en",
    "title",
    "Explore 3continents"
  ],
  [
    "achievement",
    "explore_3continents",
    "en",
    "description",
    "Visit 3 different continents"
  ],
  [
    "achievement",
    "explore_3continents",
    "zh-TW",
    "title",
    "跨洲冒險"
  ],
  [
    "achievement",
    "explore_3continents",
    "zh-TW",
    "description",
    "踏上 3 大洲"
  ],
  [
    "achievement",
    "explore_dateline",
    "en",
    "title",
    "Explore Dateline"
  ],
  [
    "achievement",
    "explore_dateline",
    "en",
    "description",
    "跨越國際換日線"
  ],
  [
    "achievement",
    "explore_dateline",
    "zh-TW",
    "title",
    "穿越換日線"
  ],
  [
    "achievement",
    "explore_dateline",
    "zh-TW",
    "description",
    "跨越國際換日線"
  ],
  [
    "achievement",
    "explore_missed_flight",
    "en",
    "title",
    "Explore Missed Flight"
  ],
  [
    "achievement",
    "explore_missed_flight",
    "en",
    "description",
    "錯過一次航班"
  ],
  [
    "achievement",
    "explore_missed_flight",
    "zh-TW",
    "title",
    "錯過班機"
  ],
  [
    "achievement",
    "explore_missed_flight",
    "zh-TW",
    "description",
    "錯過一次航班"
  ],
  [
    "achievement",
    "explore_island",
    "en",
    "title",
    "Explore Island"
  ],
  [
    "achievement",
    "explore_island",
    "en",
    "description",
    "造訪一座島嶼"
  ],
  [
    "achievement",
    "explore_island",
    "zh-TW",
    "title",
    "島嶼探險"
  ],
  [
    "achievement",
    "explore_island",
    "zh-TW",
    "description",
    "造訪一座島嶼"
  ],
  [
    "achievement",
    "explore_mountain",
    "en",
    "title",
    "Explore Mountain"
  ],
  [
    "achievement",
    "explore_mountain",
    "en",
    "description",
    "攀登一座高山"
  ],
  [
    "achievement",
    "explore_mountain",
    "zh-TW",
    "title",
    "登峰造極"
  ],
  [
    "achievement",
    "explore_mountain",
    "zh-TW",
    "description",
    "攀登一座高山"
  ],
  [
    "achievement",
    "explore_solo",
    "en",
    "title",
    "Explore Solo"
  ],
  [
    "achievement",
    "explore_solo",
    "en",
    "description",
    "完成一次獨自旅行"
  ],
  [
    "achievement",
    "explore_solo",
    "zh-TW",
    "title",
    "獨自旅行"
  ],
  [
    "achievement",
    "explore_solo",
    "zh-TW",
    "description",
    "完成一次獨自旅行"
  ],
  [
    "achievement",
    "explore_ocean",
    "en",
    "title",
    "Explore Ocean"
  ],
  [
    "achievement",
    "explore_ocean",
    "en",
    "description",
    "橫渡一片大洋"
  ],
  [
    "achievement",
    "explore_ocean",
    "zh-TW",
    "title",
    "橫渡大洋"
  ],
  [
    "achievement",
    "explore_ocean",
    "zh-TW",
    "description",
    "橫渡一片大洋"
  ],
  [
    "achievement",
    "explore_first_abroad",
    "en",
    "title",
    "Explore First Abroad"
  ],
  [
    "achievement",
    "explore_first_abroad",
    "en",
    "description",
    "第一次出國旅行"
  ],
  [
    "achievement",
    "explore_first_abroad",
    "zh-TW",
    "title",
    "首度出國"
  ],
  [
    "achievement",
    "explore_first_abroad",
    "zh-TW",
    "description",
    "第一次出國旅行"
  ],
  [
    "achievement",
    "explore_japan",
    "en",
    "title",
    "Explore Japan"
  ],
  [
    "achievement",
    "explore_japan",
    "en",
    "description",
    "造訪日本"
  ],
  [
    "achievement",
    "explore_japan",
    "zh-TW",
    "title",
    "日本漫遊"
  ],
  [
    "achievement",
    "explore_japan",
    "zh-TW",
    "description",
    "造訪日本"
  ],
  [
    "achievement",
    "explore_europe",
    "en",
    "title",
    "Explore Europe"
  ],
  [
    "achievement",
    "explore_europe",
    "en",
    "description",
    "造訪歐洲"
  ],
  [
    "achievement",
    "explore_europe",
    "zh-TW",
    "title",
    "歐洲巡禮"
  ],
  [
    "achievement",
    "explore_europe",
    "zh-TW",
    "description",
    "造訪歐洲"
  ],
  [
    "achievement",
    "explore_africa",
    "en",
    "title",
    "Explore Africa"
  ],
  [
    "achievement",
    "explore_africa",
    "en",
    "description",
    "造訪非洲"
  ],
  [
    "achievement",
    "explore_africa",
    "zh-TW",
    "title",
    "非洲探險"
  ],
  [
    "achievement",
    "explore_africa",
    "zh-TW",
    "description",
    "造訪非洲"
  ],
  [
    "achievement",
    "explore_south_america",
    "en",
    "title",
    "Explore South America"
  ],
  [
    "achievement",
    "explore_south_america",
    "en",
    "description",
    "造訪南美洲"
  ],
  [
    "achievement",
    "explore_south_america",
    "zh-TW",
    "title",
    "南美之旅"
  ],
  [
    "achievement",
    "explore_south_america",
    "zh-TW",
    "description",
    "造訪南美洲"
  ],
  [
    "achievement",
    "explore_antarctica",
    "en",
    "title",
    "Explore Antarctica"
  ],
  [
    "achievement",
    "explore_antarctica",
    "en",
    "description",
    "造訪南極洲"
  ],
  [
    "achievement",
    "explore_antarctica",
    "zh-TW",
    "title",
    "南極遠征"
  ],
  [
    "achievement",
    "explore_antarctica",
    "zh-TW",
    "description",
    "造訪南極洲"
  ],
  [
    "achievement",
    "explore_australia",
    "en",
    "title",
    "Explore Australia"
  ],
  [
    "achievement",
    "explore_australia",
    "en",
    "description",
    "造訪澳洲"
  ],
  [
    "achievement",
    "explore_australia",
    "zh-TW",
    "title",
    "澳洲歷險"
  ],
  [
    "achievement",
    "explore_australia",
    "zh-TW",
    "description",
    "造訪澳洲"
  ],
  [
    "achievement",
    "explore_asia",
    "en",
    "title",
    "Explore Asia"
  ],
  [
    "achievement",
    "explore_asia",
    "en",
    "description",
    "造訪亞洲"
  ],
  [
    "achievement",
    "explore_asia",
    "zh-TW",
    "title",
    "亞洲漫遊"
  ],
  [
    "achievement",
    "explore_asia",
    "zh-TW",
    "description",
    "造訪亞洲"
  ],
  [
    "achievement",
    "explore_north_america",
    "en",
    "title",
    "Explore North America"
  ],
  [
    "achievement",
    "explore_north_america",
    "en",
    "description",
    "造訪北美洲"
  ],
  [
    "achievement",
    "explore_north_america",
    "zh-TW",
    "title",
    "北美探險"
  ],
  [
    "achievement",
    "explore_north_america",
    "zh-TW",
    "description",
    "造訪北美洲"
  ],
  [
    "achievement",
    "explore_oceania",
    "en",
    "title",
    "Explore Oceania"
  ],
  [
    "achievement",
    "explore_oceania",
    "en",
    "description",
    "造訪大洋洲"
  ],
  [
    "achievement",
    "explore_oceania",
    "zh-TW",
    "title",
    "大洋洲之旅"
  ],
  [
    "achievement",
    "explore_oceania",
    "zh-TW",
    "description",
    "造訪大洋洲"
  ],
  [
    "achievement",
    "explore_capital",
    "en",
    "title",
    "Explore Capital"
  ],
  [
    "achievement",
    "explore_capital",
    "en",
    "description",
    "造訪一個首都城市"
  ],
  [
    "achievement",
    "explore_capital",
    "zh-TW",
    "title",
    "首都巡禮"
  ],
  [
    "achievement",
    "explore_capital",
    "zh-TW",
    "description",
    "造訪一個首都城市"
  ],
  [
    "achievement",
    "explore_unesco",
    "en",
    "title",
    "Explore Unesco"
  ],
  [
    "achievement",
    "explore_unesco",
    "en",
    "description",
    "造訪一個 UNESCO 世界遺產"
  ],
  [
    "achievement",
    "explore_unesco",
    "zh-TW",
    "title",
    "世界遺產"
  ],
  [
    "achievement",
    "explore_unesco",
    "zh-TW",
    "description",
    "造訪一個 UNESCO 世界遺產"
  ],
  [
    "achievement",
    "explore_temple",
    "en",
    "title",
    "Explore Temple"
  ],
  [
    "achievement",
    "explore_temple",
    "en",
    "description",
    "參訪一座寺廟"
  ],
  [
    "achievement",
    "explore_temple",
    "zh-TW",
    "title",
    "古剎參拜"
  ],
  [
    "achievement",
    "explore_temple",
    "zh-TW",
    "description",
    "參訪一座寺廟"
  ],
  [
    "achievement",
    "explore_night_market",
    "en",
    "title",
    "Explore Night Market"
  ],
  [
    "achievement",
    "explore_night_market",
    "en",
    "description",
    "逛一個夜市"
  ],
  [
    "achievement",
    "explore_night_market",
    "zh-TW",
    "title",
    "夜市饗宴"
  ],
  [
    "achievement",
    "explore_night_market",
    "zh-TW",
    "description",
    "逛一個夜市"
  ],
  [
    "achievement",
    "explore_hot_spring",
    "en",
    "title",
    "Explore Hot Spring"
  ],
  [
    "achievement",
    "explore_hot_spring",
    "en",
    "description",
    "泡一次溫泉"
  ],
  [
    "achievement",
    "explore_hot_spring",
    "zh-TW",
    "title",
    "溫泉之旅"
  ],
  [
    "achievement",
    "explore_hot_spring",
    "zh-TW",
    "description",
    "泡一次溫泉"
  ],
  [
    "achievement",
    "explore_beach",
    "en",
    "title",
    "Explore Beach"
  ],
  [
    "achievement",
    "explore_beach",
    "en",
    "description",
    "享受一片海灘"
  ],
  [
    "achievement",
    "explore_beach",
    "zh-TW",
    "title",
    "海灘時光"
  ],
  [
    "achievement",
    "explore_beach",
    "zh-TW",
    "description",
    "享受一片海灘"
  ],
  [
    "achievement",
    "explore_museum",
    "en",
    "title",
    "Explore Museum"
  ],
  [
    "achievement",
    "explore_museum",
    "en",
    "description",
    "參觀一個博物館"
  ],
  [
    "achievement",
    "explore_museum",
    "zh-TW",
    "title",
    "博物館日"
  ],
  [
    "achievement",
    "explore_museum",
    "zh-TW",
    "description",
    "參觀一個博物館"
  ],
  [
    "achievement",
    "explore_airport",
    "en",
    "title",
    "Explore Airport"
  ],
  [
    "achievement",
    "explore_airport",
    "en",
    "description",
    "在機場待超過 3 小時"
  ],
  [
    "achievement",
    "explore_airport",
    "zh-TW",
    "title",
    "機場漫遊"
  ],
  [
    "achievement",
    "explore_airport",
    "zh-TW",
    "description",
    "在機場待超過 3 小時"
  ],
  [
    "achievement",
    "explore_cruise",
    "en",
    "title",
    "Explore Cruise"
  ],
  [
    "achievement",
    "explore_cruise",
    "en",
    "description",
    "搭乘一次遊輪"
  ],
  [
    "achievement",
    "explore_cruise",
    "zh-TW",
    "title",
    "遊輪之旅"
  ],
  [
    "achievement",
    "explore_cruise",
    "zh-TW",
    "description",
    "搭乘一次遊輪"
  ],
  [
    "achievement",
    "explore_border",
    "en",
    "title",
    "Explore Border"
  ],
  [
    "achievement",
    "explore_border",
    "en",
    "description",
    "跨越一次國境"
  ],
  [
    "achievement",
    "explore_border",
    "zh-TW",
    "title",
    "邊境穿梭"
  ],
  [
    "achievement",
    "explore_border",
    "zh-TW",
    "description",
    "跨越一次國境"
  ],
  [
    "achievement",
    "explore_canyon",
    "en",
    "title",
    "Explore Canyon"
  ],
  [
    "achievement",
    "explore_canyon",
    "en",
    "description",
    "造訪一座峽谷"
  ],
  [
    "achievement",
    "explore_canyon",
    "zh-TW",
    "title",
    "峽谷探險"
  ],
  [
    "achievement",
    "explore_canyon",
    "zh-TW",
    "description",
    "造訪一座峽谷"
  ],
  [
    "achievement",
    "explore_volcano",
    "en",
    "title",
    "Explore Volcano"
  ],
  [
    "achievement",
    "explore_volcano",
    "en",
    "description",
    "造訪一座火山"
  ],
  [
    "achievement",
    "explore_volcano",
    "zh-TW",
    "title",
    "火山探秘"
  ],
  [
    "achievement",
    "explore_volcano",
    "zh-TW",
    "description",
    "造訪一座火山"
  ],
  [
    "achievement",
    "explore_lake",
    "en",
    "title",
    "Explore Lake"
  ],
  [
    "achievement",
    "explore_lake",
    "en",
    "description",
    "造訪一座湖泊"
  ],
  [
    "achievement",
    "explore_lake",
    "zh-TW",
    "title",
    "湖畔靜謐"
  ],
  [
    "achievement",
    "explore_lake",
    "zh-TW",
    "description",
    "造訪一座湖泊"
  ],
  [
    "achievement",
    "explore_tower",
    "en",
    "title",
    "Explore Tower"
  ],
  [
    "achievement",
    "explore_tower",
    "en",
    "description",
    "登上觀景台"
  ],
  [
    "achievement",
    "explore_tower",
    "zh-TW",
    "title",
    "登高望遠"
  ],
  [
    "achievement",
    "explore_tower",
    "zh-TW",
    "description",
    "登上觀景台"
  ],
  [
    "achievement",
    "explore_tokyo_tower",
    "en",
    "title",
    "Explore Tokyo Tower"
  ],
  [
    "achievement",
    "explore_tokyo_tower",
    "en",
    "description",
    "參訪東京鐵塔"
  ],
  [
    "achievement",
    "explore_tokyo_tower",
    "zh-TW",
    "title",
    "東京鐵塔"
  ],
  [
    "achievement",
    "explore_tokyo_tower",
    "zh-TW",
    "description",
    "參訪東京鐵塔"
  ],
  [
    "achievement",
    "explore_great_wall",
    "en",
    "title",
    "Explore Great Wall"
  ],
  [
    "achievement",
    "explore_great_wall",
    "en",
    "description",
    "親眼目睹長城"
  ],
  [
    "achievement",
    "explore_great_wall",
    "zh-TW",
    "title",
    "萬里長城"
  ],
  [
    "achievement",
    "explore_great_wall",
    "zh-TW",
    "description",
    "親眼目睹長城"
  ],
  [
    "achievement",
    "explore_venice",
    "en",
    "title",
    "Explore Venice"
  ],
  [
    "achievement",
    "explore_venice",
    "en",
    "description",
    "造訪威尼斯"
  ],
  [
    "achievement",
    "explore_venice",
    "zh-TW",
    "title",
    "水都之旅"
  ],
  [
    "achievement",
    "explore_venice",
    "zh-TW",
    "description",
    "造訪威尼斯"
  ],
  [
    "achievement",
    "ocean_pacific",
    "en",
    "title",
    "Ocean Pacific"
  ],
  [
    "achievement",
    "ocean_pacific",
    "en",
    "description",
    "造訪太平洋沿岸"
  ],
  [
    "achievement",
    "ocean_pacific",
    "zh-TW",
    "title",
    "太平洋"
  ],
  [
    "achievement",
    "ocean_pacific",
    "zh-TW",
    "description",
    "造訪太平洋沿岸"
  ],
  [
    "achievement",
    "ocean_pacific",
    "zh-TW",
    "hint",
    "東亞、美洲西岸的海域"
  ],
  [
    "achievement",
    "ocean_pacific",
    "en",
    "hint",
    "東亞、美洲西岸的海域"
  ],
  [
    "achievement",
    "ocean_atlantic",
    "en",
    "title",
    "Ocean Atlantic"
  ],
  [
    "achievement",
    "ocean_atlantic",
    "en",
    "description",
    "造訪大西洋沿岸"
  ],
  [
    "achievement",
    "ocean_atlantic",
    "zh-TW",
    "title",
    "大西洋"
  ],
  [
    "achievement",
    "ocean_atlantic",
    "zh-TW",
    "description",
    "造訪大西洋沿岸"
  ],
  [
    "achievement",
    "ocean_atlantic",
    "zh-TW",
    "hint",
    "歐洲、非洲西岸的海域"
  ],
  [
    "achievement",
    "ocean_atlantic",
    "en",
    "hint",
    "歐洲、非洲西岸的海域"
  ],
  [
    "achievement",
    "ocean_indian",
    "en",
    "title",
    "Ocean Indian"
  ],
  [
    "achievement",
    "ocean_indian",
    "en",
    "description",
    "造訪印度洋沿岸"
  ],
  [
    "achievement",
    "ocean_indian",
    "zh-TW",
    "title",
    "印度洋"
  ],
  [
    "achievement",
    "ocean_indian",
    "zh-TW",
    "description",
    "造訪印度洋沿岸"
  ],
  [
    "achievement",
    "ocean_indian",
    "zh-TW",
    "hint",
    "南亞、東非沿海的海域"
  ],
  [
    "achievement",
    "ocean_indian",
    "en",
    "hint",
    "南亞、東非沿海的海域"
  ],
  [
    "achievement",
    "ocean_arctic",
    "en",
    "title",
    "Ocean Arctic"
  ],
  [
    "achievement",
    "ocean_arctic",
    "en",
    "description",
    "造訪北冰洋沿岸"
  ],
  [
    "achievement",
    "ocean_arctic",
    "zh-TW",
    "title",
    "北冰洋"
  ],
  [
    "achievement",
    "ocean_arctic",
    "zh-TW",
    "description",
    "造訪北冰洋沿岸"
  ],
  [
    "achievement",
    "ocean_arctic",
    "zh-TW",
    "hint",
    "極北之地的冰冷海域"
  ],
  [
    "achievement",
    "ocean_arctic",
    "en",
    "hint",
    "極北之地的冰冷海域"
  ],
  [
    "achievement",
    "ocean_southern",
    "en",
    "title",
    "Ocean Southern"
  ],
  [
    "achievement",
    "ocean_southern",
    "en",
    "description",
    "造訪南冰洋沿岸"
  ],
  [
    "achievement",
    "ocean_southern",
    "zh-TW",
    "title",
    "南冰洋"
  ],
  [
    "achievement",
    "ocean_southern",
    "zh-TW",
    "description",
    "造訪南冰洋沿岸"
  ],
  [
    "achievement",
    "ocean_southern",
    "zh-TW",
    "hint",
    "環繞南極洲的極寒海域"
  ],
  [
    "achievement",
    "ocean_southern",
    "en",
    "hint",
    "環繞南極洲的極寒海域"
  ],
  [
    "achievement",
    "career_phd",
    "en",
    "title",
    "Career Phd"
  ],
  [
    "achievement",
    "career_phd",
    "en",
    "description",
    "獲得博士學位"
  ],
  [
    "achievement",
    "career_phd",
    "zh-TW",
    "title",
    "博士學位"
  ],
  [
    "achievement",
    "career_phd",
    "zh-TW",
    "description",
    "獲得博士學位"
  ],
  [
    "achievement",
    "career_graduate",
    "en",
    "title",
    "Career Graduate"
  ],
  [
    "achievement",
    "career_graduate",
    "en",
    "description",
    "大學畢業"
  ],
  [
    "achievement",
    "career_graduate",
    "zh-TW",
    "title",
    "學業有成"
  ],
  [
    "achievement",
    "career_graduate",
    "zh-TW",
    "description",
    "大學畢業"
  ],
  [
    "achievement",
    "career_house",
    "en",
    "title",
    "Career House"
  ],
  [
    "achievement",
    "career_house",
    "en",
    "description",
    "購買第一間房子"
  ],
  [
    "achievement",
    "career_house",
    "zh-TW",
    "title",
    "置產置業"
  ],
  [
    "achievement",
    "career_house",
    "zh-TW",
    "description",
    "購買第一間房子"
  ],
  [
    "achievement",
    "career_first_job",
    "en",
    "title",
    "Career First Job"
  ],
  [
    "achievement",
    "career_first_job",
    "en",
    "description",
    "獲得第一份工作"
  ],
  [
    "achievement",
    "career_first_job",
    "zh-TW",
    "title",
    "踏入職場"
  ],
  [
    "achievement",
    "career_first_job",
    "zh-TW",
    "description",
    "獲得第一份工作"
  ],
  [
    "achievement",
    "career_365_ontime",
    "en",
    "title",
    "Career 365 Ontime"
  ],
  [
    "achievement",
    "career_365_ontime",
    "en",
    "description",
    "連續一年準時上班"
  ],
  [
    "achievement",
    "career_365_ontime",
    "zh-TW",
    "title",
    "全勤達人"
  ],
  [
    "achievement",
    "career_365_ontime",
    "zh-TW",
    "description",
    "連續一年準時上班"
  ],
  [
    "achievement",
    "career_masters",
    "en",
    "title",
    "Career Masters"
  ],
  [
    "achievement",
    "career_masters",
    "en",
    "description",
    "獲得碩士學位"
  ],
  [
    "achievement",
    "career_masters",
    "zh-TW",
    "title",
    "碩士學位"
  ],
  [
    "achievement",
    "career_masters",
    "zh-TW",
    "description",
    "獲得碩士學位"
  ],
  [
    "achievement",
    "career_bachelor",
    "en",
    "title",
    "Career Bachelor"
  ],
  [
    "achievement",
    "career_bachelor",
    "en",
    "description",
    "獲得學士學位"
  ],
  [
    "achievement",
    "career_bachelor",
    "zh-TW",
    "title",
    "學士學位"
  ],
  [
    "achievement",
    "career_bachelor",
    "zh-TW",
    "description",
    "獲得學士學位"
  ],
  [
    "achievement",
    "career_fired",
    "en",
    "title",
    "Career Fired"
  ],
  [
    "achievement",
    "career_fired",
    "en",
    "description",
    "被公司解僱"
  ],
  [
    "achievement",
    "career_fired",
    "zh-TW",
    "title",
    "被開除了"
  ],
  [
    "achievement",
    "career_fired",
    "zh-TW",
    "description",
    "被公司解僱"
  ],
  [
    "achievement",
    "career_promotion",
    "en",
    "title",
    "Career Promotion"
  ],
  [
    "achievement",
    "career_promotion",
    "en",
    "description",
    "獲得一次升職"
  ],
  [
    "achievement",
    "career_promotion",
    "zh-TW",
    "title",
    "升職加薪"
  ],
  [
    "achievement",
    "career_promotion",
    "zh-TW",
    "description",
    "獲得一次升職"
  ],
  [
    "achievement",
    "career_startup",
    "en",
    "title",
    "Career Startup"
  ],
  [
    "achievement",
    "career_startup",
    "en",
    "description",
    "創辦一家公司"
  ],
  [
    "achievement",
    "career_startup",
    "zh-TW",
    "title",
    "創業先鋒"
  ],
  [
    "achievement",
    "career_startup",
    "zh-TW",
    "description",
    "創辦一家公司"
  ],
  [
    "achievement",
    "career_raise",
    "en",
    "title",
    "Career Raise"
  ],
  [
    "achievement",
    "career_raise",
    "en",
    "description",
    "成功爭取加薪"
  ],
  [
    "achievement",
    "career_raise",
    "zh-TW",
    "title",
    "談判大師"
  ],
  [
    "achievement",
    "career_raise",
    "zh-TW",
    "description",
    "成功爭取加薪"
  ],
  [
    "achievement",
    "career_quit",
    "en",
    "title",
    "Career Quit"
  ],
  [
    "achievement",
    "career_quit",
    "en",
    "description",
    "裸辭一次"
  ],
  [
    "achievement",
    "career_quit",
    "zh-TW",
    "title",
    "華麗轉身"
  ],
  [
    "achievement",
    "career_quit",
    "zh-TW",
    "description",
    "裸辭一次"
  ],
  [
    "achievement",
    "career_meeting_hell",
    "en",
    "title",
    "Career Meeting Hell"
  ],
  [
    "achievement",
    "career_meeting_hell",
    "en",
    "description",
    "一天開 5 場會"
  ],
  [
    "achievement",
    "career_meeting_hell",
    "zh-TW",
    "title",
    "會議地獄"
  ],
  [
    "achievement",
    "career_meeting_hell",
    "zh-TW",
    "description",
    "一天開 5 場會"
  ],
  [
    "achievement",
    "daily_lottery",
    "en",
    "title",
    "Daily Lottery"
  ],
  [
    "achievement",
    "daily_lottery",
    "en",
    "description",
    "中一次發票"
  ],
  [
    "achievement",
    "daily_lottery",
    "zh-TW",
    "title",
    "發票中獎"
  ],
  [
    "achievement",
    "daily_lottery",
    "zh-TW",
    "description",
    "中一次發票"
  ],
  [
    "achievement",
    "daily_social",
    "en",
    "title",
    "Daily Social"
  ],
  [
    "achievement",
    "daily_social",
    "en",
    "description",
    "參加一場社交活動"
  ],
  [
    "achievement",
    "daily_social",
    "zh-TW",
    "title",
    "社交達人"
  ],
  [
    "achievement",
    "daily_social",
    "zh-TW",
    "description",
    "參加一場社交活動"
  ],
  [
    "achievement",
    "daily_pets",
    "en",
    "title",
    "Daily Pets"
  ],
  [
    "achievement",
    "daily_pets",
    "en",
    "description",
    "養 2 隻寵物"
  ],
  [
    "achievement",
    "daily_pets",
    "zh-TW",
    "title",
    "毛孩夥伴"
  ],
  [
    "achievement",
    "daily_pets",
    "zh-TW",
    "description",
    "養 2 隻寵物"
  ],
  [
    "achievement",
    "daily_earlybird",
    "en",
    "title",
    "Daily Earlybird"
  ],
  [
    "achievement",
    "daily_earlybird",
    "en",
    "description",
    "清晨 5 點前起床"
  ],
  [
    "achievement",
    "daily_earlybird",
    "zh-TW",
    "title",
    "早起的鳥兒"
  ],
  [
    "achievement",
    "daily_earlybird",
    "zh-TW",
    "description",
    "清晨 5 點前起床"
  ],
  [
    "achievement",
    "daily_cook",
    "en",
    "title",
    "Daily Cook"
  ],
  [
    "achievement",
    "daily_cook",
    "en",
    "description",
    "自己煮一餐"
  ],
  [
    "achievement",
    "daily_cook",
    "zh-TW",
    "title",
    "自煮生活"
  ],
  [
    "achievement",
    "daily_cook",
    "zh-TW",
    "description",
    "自己煮一餐"
  ],
  [
    "achievement",
    "daily_binge",
    "en",
    "title",
    "Daily Binge"
  ],
  [
    "achievement",
    "daily_binge",
    "en",
    "description",
    "一次看 10 集以上"
  ],
  [
    "achievement",
    "daily_binge",
    "zh-TW",
    "title",
    "追劇馬拉松"
  ],
  [
    "achievement",
    "daily_binge",
    "zh-TW",
    "description",
    "一次看 10 集以上"
  ],
  [
    "achievement",
    "daily_allnighter",
    "en",
    "title",
    "Daily Allnighter"
  ],
  [
    "achievement",
    "daily_allnighter",
    "en",
    "description",
    "通宵一次"
  ],
  [
    "achievement",
    "daily_allnighter",
    "zh-TW",
    "title",
    "徹夜未眠"
  ],
  [
    "achievement",
    "daily_allnighter",
    "zh-TW",
    "description",
    "通宵一次"
  ],
  [
    "achievement",
    "daily_exercise_30",
    "en",
    "title",
    "Daily Exercise 30"
  ],
  [
    "achievement",
    "daily_exercise_30",
    "en",
    "description",
    "連續運動 30 分鐘"
  ],
  [
    "achievement",
    "daily_exercise_30",
    "zh-TW",
    "title",
    "運動習慣"
  ],
  [
    "achievement",
    "daily_exercise_30",
    "zh-TW",
    "description",
    "連續運動 30 分鐘"
  ],
  [
    "achievement",
    "daily_read_10",
    "en",
    "title",
    "Daily Read 10"
  ],
  [
    "achievement",
    "daily_read_10",
    "en",
    "description",
    "讀完 10 本書"
  ],
  [
    "achievement",
    "daily_read_10",
    "zh-TW",
    "title",
    "閱讀時光"
  ],
  [
    "achievement",
    "daily_read_10",
    "zh-TW",
    "description",
    "讀完 10 本書"
  ],
  [
    "achievement",
    "daily_no_phone",
    "en",
    "title",
    "Daily No Phone"
  ],
  [
    "achievement",
    "daily_no_phone",
    "en",
    "description",
    "一整天不用手機"
  ],
  [
    "achievement",
    "daily_no_phone",
    "zh-TW",
    "title",
    "數位排毒"
  ],
  [
    "achievement",
    "daily_no_phone",
    "zh-TW",
    "description",
    "一整天不用手機"
  ],
  [
    "achievement",
    "daily_stranger",
    "en",
    "title",
    "Daily Stranger"
  ],
  [
    "achievement",
    "daily_stranger",
    "en",
    "description",
    "幫助一位陌生人"
  ],
  [
    "achievement",
    "daily_stranger",
    "zh-TW",
    "title",
    "陌生善意"
  ],
  [
    "achievement",
    "daily_stranger",
    "zh-TW",
    "description",
    "幫助一位陌生人"
  ],
  [
    "achievement",
    "daily_umbrella",
    "en",
    "title",
    "Daily Umbrella"
  ],
  [
    "achievement",
    "daily_umbrella",
    "en",
    "description",
    "弄丟一把雨傘"
  ],
  [
    "achievement",
    "daily_umbrella",
    "zh-TW",
    "title",
    "雨傘收藏家"
  ],
  [
    "achievement",
    "daily_umbrella",
    "zh-TW",
    "description",
    "弄丟一把雨傘"
  ],
  [
    "achievement",
    "daily_puzzle",
    "en",
    "title",
    "Daily Puzzle"
  ],
  [
    "achievement",
    "daily_puzzle",
    "en",
    "description",
    "完成一個拼圖"
  ],
  [
    "achievement",
    "daily_puzzle",
    "zh-TW",
    "title",
    "拼圖挑戰"
  ],
  [
    "achievement",
    "daily_puzzle",
    "zh-TW",
    "description",
    "完成一個拼圖"
  ],
  [
    "achievement",
    "daily_late",
    "en",
    "title",
    "Daily Late"
  ],
  [
    "achievement",
    "daily_late",
    "en",
    "description",
    "遲到超過 30 分鐘"
  ],
  [
    "achievement",
    "daily_late",
    "zh-TW",
    "title",
    "時間旅人"
  ],
  [
    "achievement",
    "daily_late",
    "zh-TW",
    "description",
    "遲到超過 30 分鐘"
  ],
  [
    "achievement",
    "daily_spicy",
    "en",
    "title",
    "Daily Spicy"
  ],
  [
    "achievement",
    "daily_spicy",
    "en",
    "description",
    "吃完一碗麻辣鍋"
  ],
  [
    "achievement",
    "daily_spicy",
    "zh-TW",
    "title",
    "地獄級挑戰"
  ],
  [
    "achievement",
    "daily_spicy",
    "zh-TW",
    "description",
    "吃完一碗麻辣鍋"
  ],
  [
    "achievement",
    "daily_karaoke",
    "en",
    "title",
    "Daily Karaoke"
  ],
  [
    "achievement",
    "daily_karaoke",
    "en",
    "description",
    "在 KTV 唱完一首歌"
  ],
  [
    "achievement",
    "daily_karaoke",
    "zh-TW",
    "title",
    "浴室歌王"
  ],
  [
    "achievement",
    "daily_karaoke",
    "zh-TW",
    "description",
    "在 KTV 唱完一首歌"
  ],
  [
    "achievement",
    "daily_fall_down",
    "en",
    "title",
    "Daily Fall Down"
  ],
  [
    "achievement",
    "daily_fall_down",
    "en",
    "description",
    "在公共場合跌倒"
  ],
  [
    "achievement",
    "daily_fall_down",
    "zh-TW",
    "title",
    "仆街達人"
  ],
  [
    "achievement",
    "daily_fall_down",
    "zh-TW",
    "description",
    "在公共場合跌倒"
  ],
  [
    "achievement",
    "epic_eclipse",
    "en",
    "title",
    "Epic Eclipse"
  ],
  [
    "achievement",
    "epic_eclipse",
    "en",
    "description",
    "親眼目睹日蝕或月蝕"
  ],
  [
    "achievement",
    "epic_eclipse",
    "zh-TW",
    "title",
    "日月蝕"
  ],
  [
    "achievement",
    "epic_eclipse",
    "zh-TW",
    "description",
    "親眼目睹日蝕或月蝕"
  ],
  [
    "achievement",
    "epic_eclipse",
    "zh-TW",
    "hint",
    "天空中的光影奇觀"
  ],
  [
    "achievement",
    "epic_eclipse",
    "en",
    "hint",
    "天空中的光影奇觀"
  ],
  [
    "achievement",
    "epic_survive",
    "en",
    "title",
    "Epic Survive"
  ],
  [
    "achievement",
    "epic_survive",
    "en",
    "description",
    "經歷一次生死關頭"
  ],
  [
    "achievement",
    "epic_survive",
    "zh-TW",
    "title",
    "死裡逃生"
  ],
  [
    "achievement",
    "epic_survive",
    "zh-TW",
    "description",
    "經歷一次生死關頭"
  ],
  [
    "achievement",
    "epic_survive",
    "zh-TW",
    "hint",
    "從最危險的處境中活下來"
  ],
  [
    "achievement",
    "epic_survive",
    "en",
    "hint",
    "從最危險的處境中活下來"
  ],
  [
    "achievement",
    "epic_newborn",
    "en",
    "title",
    "Epic Newborn"
  ],
  [
    "achievement",
    "epic_newborn",
    "en",
    "description",
    "迎接新生兒"
  ],
  [
    "achievement",
    "epic_newborn",
    "zh-TW",
    "title",
    "新生命"
  ],
  [
    "achievement",
    "epic_newborn",
    "zh-TW",
    "description",
    "迎接新生兒"
  ],
  [
    "achievement",
    "epic_newborn",
    "zh-TW",
    "hint",
    "一個小小的生命來到這個世界"
  ],
  [
    "achievement",
    "epic_newborn",
    "en",
    "hint",
    "一個小小的生命來到這個世界"
  ],
  [
    "achievement",
    "epic_northernlights",
    "en",
    "title",
    "Epic Northernlights"
  ],
  [
    "achievement",
    "epic_northernlights",
    "en",
    "description",
    "親眼目睹極光"
  ],
  [
    "achievement",
    "epic_northernlights",
    "zh-TW",
    "title",
    "極光奇景"
  ],
  [
    "achievement",
    "epic_northernlights",
    "zh-TW",
    "description",
    "親眼目睹極光"
  ],
  [
    "achievement",
    "epic_northernlights",
    "zh-TW",
    "hint",
    "高緯度地區的夢幻光幕"
  ],
  [
    "achievement",
    "epic_northernlights",
    "en",
    "hint",
    "高緯度地區的夢幻光幕"
  ],
  [
    "achievement",
    "epic_milkyway",
    "en",
    "title",
    "Epic Milkyway"
  ],
  [
    "achievement",
    "epic_milkyway",
    "en",
    "description",
    "親眼看見銀河"
  ],
  [
    "achievement",
    "epic_milkyway",
    "zh-TW",
    "title",
    "銀河之旅"
  ],
  [
    "achievement",
    "epic_milkyway",
    "zh-TW",
    "description",
    "親眼看見銀河"
  ],
  [
    "achievement",
    "epic_milkyway",
    "zh-TW",
    "hint",
    "遠離光害的星空奇景"
  ],
  [
    "achievement",
    "epic_milkyway",
    "en",
    "hint",
    "遠離光害的星空奇景"
  ],
  [
    "achievement",
    "epic_earthquake",
    "en",
    "title",
    "Epic Earthquake"
  ],
  [
    "achievement",
    "epic_earthquake",
    "en",
    "description",
    "經歷一次地震"
  ],
  [
    "achievement",
    "epic_earthquake",
    "zh-TW",
    "title",
    "地牛翻身"
  ],
  [
    "achievement",
    "epic_earthquake",
    "zh-TW",
    "description",
    "經歷一次地震"
  ],
  [
    "achievement",
    "weather_storm",
    "en",
    "title",
    "Weather Storm"
  ],
  [
    "achievement",
    "weather_storm",
    "en",
    "description",
    "所在地區有暴風或颱風警報"
  ],
  [
    "achievement",
    "weather_storm",
    "zh-TW",
    "title",
    "暴風來襲"
  ],
  [
    "achievement",
    "weather_storm",
    "zh-TW",
    "description",
    "所在地區有暴風或颱風警報"
  ],
  [
    "achievement",
    "weather_rain",
    "en",
    "title",
    "Weather Rain"
  ],
  [
    "achievement",
    "weather_rain",
    "en",
    "description",
    "今天下雨了"
  ],
  [
    "achievement",
    "weather_rain",
    "zh-TW",
    "title",
    "雨中漫步"
  ],
  [
    "achievement",
    "weather_rain",
    "zh-TW",
    "description",
    "今天下雨了"
  ],
  [
    "achievement",
    "weather_extreme_heat",
    "en",
    "title",
    "Weather Extreme Heat"
  ],
  [
    "achievement",
    "weather_extreme_heat",
    "en",
    "description",
    "今天最高溫超過 35 度"
  ],
  [
    "achievement",
    "weather_extreme_heat",
    "zh-TW",
    "title",
    "熱浪考驗"
  ],
  [
    "achievement",
    "weather_extreme_heat",
    "zh-TW",
    "description",
    "今天最高溫超過 35 度"
  ],
  [
    "achievement",
    "weather_lightning",
    "en",
    "title",
    "Weather Lightning"
  ],
  [
    "achievement",
    "weather_lightning",
    "en",
    "description",
    "所在地區有閃電活動"
  ],
  [
    "achievement",
    "weather_lightning",
    "zh-TW",
    "title",
    "雷神降臨"
  ],
  [
    "achievement",
    "weather_lightning",
    "zh-TW",
    "description",
    "所在地區有閃電活動"
  ],
  [
    "achievement",
    "epic_double_rainbow",
    "en",
    "title",
    "Epic Double Rainbow"
  ],
  [
    "achievement",
    "epic_double_rainbow",
    "en",
    "description",
    "親眼目睹雙彩虹"
  ],
  [
    "achievement",
    "epic_double_rainbow",
    "zh-TW",
    "title",
    "雙彩虹"
  ],
  [
    "achievement",
    "epic_double_rainbow",
    "zh-TW",
    "description",
    "親眼目睹雙彩虹"
  ],
  [
    "achievement",
    "epic_meteor",
    "en",
    "title",
    "Epic Meteor"
  ],
  [
    "achievement",
    "epic_meteor",
    "en",
    "description",
    "親眼目睹流星雨"
  ],
  [
    "achievement",
    "epic_meteor",
    "zh-TW",
    "title",
    "流星雨"
  ],
  [
    "achievement",
    "epic_meteor",
    "zh-TW",
    "description",
    "親眼目睹流星雨"
  ],
  [
    "achievement",
    "epic_first_date",
    "en",
    "title",
    "Epic First Date"
  ],
  [
    "achievement",
    "epic_first_date",
    "en",
    "description",
    "完成第一次約會"
  ],
  [
    "achievement",
    "epic_first_date",
    "zh-TW",
    "title",
    "初戀滋味"
  ],
  [
    "achievement",
    "epic_first_date",
    "zh-TW",
    "description",
    "完成第一次約會"
  ],
  [
    "achievement",
    "epic_concert",
    "en",
    "title",
    "Epic Concert"
  ],
  [
    "achievement",
    "epic_concert",
    "en",
    "description",
    "參加一場大型演唱會"
  ],
  [
    "achievement",
    "epic_concert",
    "zh-TW",
    "title",
    "現場實況"
  ],
  [
    "achievement",
    "epic_concert",
    "zh-TW",
    "description",
    "參加一場大型演唱會"
  ],
  [
    "achievement",
    "health_marathon",
    "en",
    "title",
    "Health Marathon"
  ],
  [
    "achievement",
    "health_marathon",
    "en",
    "description",
    "完成一場馬拉松"
  ],
  [
    "achievement",
    "health_marathon",
    "zh-TW",
    "title",
    "馬拉松跑者"
  ],
  [
    "achievement",
    "health_marathon",
    "zh-TW",
    "description",
    "完成一場馬拉松"
  ],
  [
    "achievement",
    "health_blood",
    "en",
    "title",
    "Health Blood"
  ],
  [
    "achievement",
    "health_blood",
    "en",
    "description",
    "捐血一次"
  ],
  [
    "achievement",
    "health_blood",
    "zh-TW",
    "title",
    "熱血助人"
  ],
  [
    "achievement",
    "health_blood",
    "zh-TW",
    "description",
    "捐血一次"
  ],
  [
    "achievement",
    "health_10k",
    "en",
    "title",
    "Health 10k"
  ],
  [
    "achievement",
    "health_10k",
    "en",
    "description",
    "跑完 10 公里"
  ],
  [
    "achievement",
    "health_10k",
    "zh-TW",
    "title",
    "十公里挑戰"
  ],
  [
    "achievement",
    "health_10k",
    "zh-TW",
    "description",
    "跑完 10 公里"
  ],
  [
    "achievement",
    "health_no_sugar",
    "en",
    "title",
    "Health No Sugar"
  ],
  [
    "achievement",
    "health_no_sugar",
    "en",
    "description",
    "連續一週不吃糖"
  ],
  [
    "achievement",
    "health_no_sugar",
    "zh-TW",
    "title",
    "戒糖挑戰"
  ],
  [
    "achievement",
    "health_no_sugar",
    "zh-TW",
    "description",
    "連續一週不吃糖"
  ],
  [
    "achievement",
    "health_meditate",
    "en",
    "title",
    "Health Meditate"
  ],
  [
    "achievement",
    "health_meditate",
    "en",
    "description",
    "連續 30 天冥想"
  ],
  [
    "achievement",
    "health_meditate",
    "zh-TW",
    "title",
    "靜心冥想"
  ],
  [
    "achievement",
    "health_meditate",
    "zh-TW",
    "description",
    "連續 30 天冥想"
  ],
  [
    "achievement",
    "health_gym",
    "en",
    "title",
    "Health Gym"
  ],
  [
    "achievement",
    "health_gym",
    "en",
    "description",
    "開始去健身房"
  ],
  [
    "achievement",
    "health_gym",
    "zh-TW",
    "title",
    "健身新手"
  ],
  [
    "achievement",
    "health_gym",
    "zh-TW",
    "description",
    "開始去健身房"
  ],
  [
    "achievement",
    "health_pushup_50",
    "en",
    "title",
    "Health Pushup 50"
  ],
  [
    "achievement",
    "health_pushup_50",
    "en",
    "description",
    "一次完成 50 個伏地挺身"
  ],
  [
    "achievement",
    "health_pushup_50",
    "zh-TW",
    "title",
    "伏地挺身"
  ],
  [
    "achievement",
    "health_pushup_50",
    "zh-TW",
    "description",
    "一次完成 50 個伏地挺身"
  ],
  [
    "achievement",
    "health_weight_loss",
    "en",
    "title",
    "Health Weight Loss"
  ],
  [
    "achievement",
    "health_weight_loss",
    "en",
    "description",
    "成功減重 10 公斤"
  ],
  [
    "achievement",
    "health_weight_loss",
    "zh-TW",
    "title",
    "瘦身有成"
  ],
  [
    "achievement",
    "health_weight_loss",
    "zh-TW",
    "description",
    "成功減重 10 公斤"
  ],
  [
    "achievement",
    "health_sleep_8h",
    "en",
    "title",
    "Health Sleep 8h"
  ],
  [
    "achievement",
    "health_sleep_8h",
    "en",
    "description",
    "連續一週睡眠滿 8 小時"
  ],
  [
    "achievement",
    "health_sleep_8h",
    "zh-TW",
    "title",
    "睡飽飽"
  ],
  [
    "achievement",
    "health_sleep_8h",
    "zh-TW",
    "description",
    "連續一週睡眠滿 8 小時"
  ],
  [
    "achievement",
    "transport_license",
    "en",
    "title",
    "Transport License"
  ],
  [
    "achievement",
    "transport_license",
    "en",
    "description",
    "考取駕照"
  ],
  [
    "achievement",
    "transport_license",
    "zh-TW",
    "title",
    "駕照到手"
  ],
  [
    "achievement",
    "transport_license",
    "zh-TW",
    "description",
    "考取駕照"
  ],
  [
    "achievement",
    "transport_first_car",
    "en",
    "title",
    "Transport First Car"
  ],
  [
    "achievement",
    "transport_first_car",
    "en",
    "description",
    "購買第一輛車"
  ],
  [
    "achievement",
    "transport_first_car",
    "zh-TW",
    "title",
    "第一台車"
  ],
  [
    "achievement",
    "transport_first_car",
    "zh-TW",
    "description",
    "購買第一輛車"
  ],
  [
    "achievement",
    "transport_bike",
    "en",
    "title",
    "Transport Bike"
  ],
  [
    "achievement",
    "transport_bike",
    "en",
    "description",
    "騎單車通勤"
  ],
  [
    "achievement",
    "transport_bike",
    "zh-TW",
    "title",
    "單車旅人"
  ],
  [
    "achievement",
    "transport_bike",
    "zh-TW",
    "description",
    "騎單車通勤"
  ],
  [
    "achievement",
    "transport_roadtrip",
    "en",
    "title",
    "Transport Roadtrip"
  ],
  [
    "achievement",
    "transport_roadtrip",
    "en",
    "description",
    "完成一次公路旅行"
  ],
  [
    "achievement",
    "transport_roadtrip",
    "zh-TW",
    "title",
    "公路旅行"
  ],
  [
    "achievement",
    "transport_roadtrip",
    "zh-TW",
    "description",
    "完成一次公路旅行"
  ],
  [
    "achievement",
    "transport_no_accident",
    "en",
    "title",
    "Transport No Accident"
  ],
  [
    "achievement",
    "transport_no_accident",
    "en",
    "description",
    "一年無事故"
  ],
  [
    "achievement",
    "transport_no_accident",
    "zh-TW",
    "title",
    "安全駕駛"
  ],
  [
    "achievement",
    "transport_no_accident",
    "zh-TW",
    "description",
    "一年無事故"
  ],
  [
    "achievement",
    "transport_uber_100",
    "en",
    "title",
    "Transport Uber 100"
  ],
  [
    "achievement",
    "transport_uber_100",
    "en",
    "description",
    "搭乘 100 次叫車服務"
  ],
  [
    "achievement",
    "transport_uber_100",
    "zh-TW",
    "title",
    "叫車之王"
  ],
  [
    "achievement",
    "transport_uber_100",
    "zh-TW",
    "description",
    "搭乘 100 次叫車服務"
  ],
  [
    "achievement",
    "transport_bike_100",
    "en",
    "title",
    "Transport Bike 100"
  ],
  [
    "achievement",
    "transport_bike_100",
    "en",
    "description",
    "累積騎行 100 公里"
  ],
  [
    "achievement",
    "transport_bike_100",
    "zh-TW",
    "title",
    "單車百公里"
  ],
  [
    "achievement",
    "transport_bike_100",
    "zh-TW",
    "description",
    "累積騎行 100 公里"
  ],
  [
    "achievement",
    "health_yoga",
    "en",
    "title",
    "Health Yoga"
  ],
  [
    "achievement",
    "health_yoga",
    "en",
    "description",
    "完成一堂瑜伽課"
  ],
  [
    "achievement",
    "health_yoga",
    "zh-TW",
    "title",
    "瑜伽修行"
  ],
  [
    "achievement",
    "health_yoga",
    "zh-TW",
    "description",
    "完成一堂瑜伽課"
  ],
  [
    "achievement",
    "health_vegan",
    "en",
    "title",
    "Health Vegan"
  ],
  [
    "achievement",
    "health_vegan",
    "en",
    "description",
    "連續一個月素食"
  ],
  [
    "achievement",
    "health_vegan",
    "zh-TW",
    "title",
    "素食挑戰"
  ],
  [
    "achievement",
    "health_vegan",
    "zh-TW",
    "description",
    "連續一個月素食"
  ],
  [
    "achievement",
    "health_plank_5min",
    "en",
    "title",
    "Health Plank 5min"
  ],
  [
    "achievement",
    "health_plank_5min",
    "en",
    "description",
    "平板支撐超過 5 分鐘"
  ],
  [
    "achievement",
    "health_plank_5min",
    "zh-TW",
    "title",
    "核心之王"
  ],
  [
    "achievement",
    "health_plank_5min",
    "zh-TW",
    "description",
    "平板支撐超過 5 分鐘"
  ],
  [
    "achievement",
    "daily_look_up",
    "en",
    "title",
    "Daily Look Up"
  ],
  [
    "achievement",
    "daily_look_up",
    "en",
    "description",
    "抬頭看星星超過 10 分鐘"
  ],
  [
    "achievement",
    "daily_look_up",
    "zh-TW",
    "title",
    "仰望星空"
  ],
  [
    "achievement",
    "daily_look_up",
    "zh-TW",
    "description",
    "抬頭看星星超過 10 分鐘"
  ],
  [
    "achievement",
    "daily_suntan",
    "en",
    "title",
    "Daily Suntan"
  ],
  [
    "achievement",
    "daily_suntan",
    "en",
    "description",
    "在海灘曬傷"
  ],
  [
    "achievement",
    "daily_suntan",
    "zh-TW",
    "title",
    "曬黑一族"
  ],
  [
    "achievement",
    "daily_suntan",
    "zh-TW",
    "description",
    "在海灘曬傷"
  ],
  [
    "achievement",
    "daily_chopsticks",
    "en",
    "title",
    "Daily Chopsticks"
  ],
  [
    "achievement",
    "daily_chopsticks",
    "en",
    "description",
    "用筷子夾起豆腐不碎"
  ],
  [
    "achievement",
    "daily_chopsticks",
    "zh-TW",
    "title",
    "筷子達人"
  ],
  [
    "achievement",
    "daily_chopsticks",
    "zh-TW",
    "description",
    "用筷子夾起豆腐不碎"
  ],
  [
    "achievement",
    "career_overtime_hell",
    "en",
    "title",
    "Career Overtime Hell"
  ],
  [
    "achievement",
    "career_overtime_hell",
    "en",
    "description",
    "連續一個月每天加班 3 小時"
  ],
  [
    "achievement",
    "career_overtime_hell",
    "zh-TW",
    "title",
    "加班地獄"
  ],
  [
    "achievement",
    "career_overtime_hell",
    "zh-TW",
    "description",
    "連續一個月每天加班 3 小時"
  ],
  [
    "achievement",
    "career_presentation",
    "en",
    "title",
    "Career Presentation"
  ],
  [
    "achievement",
    "career_presentation",
    "en",
    "description",
    "在超過 50 人面前簡報"
  ],
  [
    "achievement",
    "career_presentation",
    "zh-TW",
    "title",
    "簡報之王"
  ],
  [
    "achievement",
    "career_presentation",
    "zh-TW",
    "description",
    "在超過 50 人面前簡報"
  ],
  [
    "achievement",
    "explore_bucket_list",
    "en",
    "title",
    "Explore Bucket List"
  ],
  [
    "achievement",
    "explore_bucket_list",
    "en",
    "description",
    "完成一件人生願望清單"
  ],
  [
    "achievement",
    "explore_bucket_list",
    "zh-TW",
    "title",
    "心願達成"
  ],
  [
    "achievement",
    "explore_bucket_list",
    "zh-TW",
    "description",
    "完成一件人生願望清單"
  ],
  [
    "achievement",
    "explore_sky_lantern",
    "en",
    "title",
    "Explore Sky Lantern"
  ],
  [
    "achievement",
    "explore_sky_lantern",
    "en",
    "description",
    "親手放天燈"
  ],
  [
    "achievement",
    "explore_sky_lantern",
    "zh-TW",
    "title",
    "天燈祈願"
  ],
  [
    "achievement",
    "explore_sky_lantern",
    "zh-TW",
    "description",
    "親手放天燈"
  ],
  [
    "achievement",
    "explore_snow",
    "en",
    "title",
    "Explore Snow"
  ],
  [
    "achievement",
    "explore_snow",
    "en",
    "description",
    "第一次看到雪"
  ],
  [
    "achievement",
    "explore_snow",
    "zh-TW",
    "title",
    "初見雪景"
  ],
  [
    "achievement",
    "explore_snow",
    "zh-TW",
    "description",
    "第一次看到雪"
  ],
  [
    "achievement",
    "explore_desert",
    "en",
    "title",
    "Explore Desert"
  ],
  [
    "achievement",
    "explore_desert",
    "en",
    "description",
    "踏上沙漠"
  ],
  [
    "achievement",
    "explore_desert",
    "zh-TW",
    "title",
    "沙漠足跡"
  ],
  [
    "achievement",
    "explore_desert",
    "zh-TW",
    "description",
    "踏上沙漠"
  ],
  [
    "achievement",
    "explore_jungle",
    "en",
    "title",
    "Explore Jungle"
  ],
  [
    "achievement",
    "explore_jungle",
    "en",
    "description",
    "深入熱帶雨林"
  ],
  [
    "achievement",
    "explore_jungle",
    "zh-TW",
    "title",
    "叢林冒險"
  ],
  [
    "achievement",
    "explore_jungle",
    "zh-TW",
    "description",
    "深入熱帶雨林"
  ],
  [
    "achievement",
    "explore_underwater",
    "en",
    "title",
    "Explore Underwater"
  ],
  [
    "achievement",
    "explore_underwater",
    "en",
    "description",
    "潛水探索海洋"
  ],
  [
    "achievement",
    "explore_underwater",
    "zh-TW",
    "title",
    "海底世界"
  ],
  [
    "achievement",
    "explore_underwater",
    "zh-TW",
    "description",
    "潛水探索海洋"
  ],
  [
    "achievement",
    "explore_camping",
    "en",
    "title",
    "Explore Camping"
  ],
  [
    "achievement",
    "explore_camping",
    "en",
    "description",
    "完成一次野外露營"
  ],
  [
    "achievement",
    "explore_camping",
    "zh-TW",
    "title",
    "星空露營"
  ],
  [
    "achievement",
    "explore_camping",
    "zh-TW",
    "description",
    "完成一次野外露營"
  ],
  [
    "achievement",
    "daily_diy",
    "en",
    "title",
    "Daily Diy"
  ],
  [
    "achievement",
    "daily_diy",
    "en",
    "description",
    "自己動手 DIY 一件物品"
  ],
  [
    "achievement",
    "daily_diy",
    "zh-TW",
    "title",
    "手作達人"
  ],
  [
    "achievement",
    "daily_diy",
    "zh-TW",
    "description",
    "自己動手 DIY 一件物品"
  ],
  [
    "achievement",
    "daily_fix",
    "en",
    "title",
    "Daily Fix"
  ],
  [
    "achievement",
    "daily_fix",
    "en",
    "description",
    "自己修理家電"
  ],
  [
    "achievement",
    "daily_fix",
    "zh-TW",
    "title",
    "修理之王"
  ],
  [
    "achievement",
    "daily_fix",
    "zh-TW",
    "description",
    "自己修理家電"
  ],
  [
    "achievement",
    "daily_plant",
    "en",
    "title",
    "Daily Plant"
  ],
  [
    "achievement",
    "daily_plant",
    "en",
    "description",
    "成功養活一盆植物超過一年"
  ],
  [
    "achievement",
    "daily_plant",
    "zh-TW",
    "title",
    "綠手指"
  ],
  [
    "achievement",
    "daily_plant",
    "zh-TW",
    "description",
    "成功養活一盆植物超過一年"
  ],
  [
    "achievement",
    "daily_tattoo",
    "en",
    "title",
    "Daily Tattoo"
  ],
  [
    "achievement",
    "daily_tattoo",
    "en",
    "description",
    "完成第一個刺青"
  ],
  [
    "achievement",
    "daily_tattoo",
    "zh-TW",
    "title",
    "身體藝術"
  ],
  [
    "achievement",
    "daily_tattoo",
    "zh-TW",
    "description",
    "完成第一個刺青"
  ],
  [
    "achievement",
    "daily_photo_album",
    "en",
    "title",
    "Daily Photo Album"
  ],
  [
    "achievement",
    "daily_photo_album",
    "en",
    "description",
    "整理一本實體相簿"
  ],
  [
    "achievement",
    "daily_photo_album",
    "zh-TW",
    "title",
    "回憶收集者"
  ],
  [
    "achievement",
    "daily_photo_album",
    "zh-TW",
    "description",
    "整理一本實體相簿"
  ]
];

export const ACHIEVEMENT_COUNT = 129;
